apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent

spec:
  replicas: 1

  image:
    application: confluentinc/cp-server:7.6.0
    init: confluentinc/confluent-init-container:2.9.0

  dataVolumeCapacity: 10Gi

  listeners:
    internal:
      tls:
        enabled: false

    external:
      tls:
        enabled: false

  dependencies:
    zookeeper:
      endpoint: zookeeper.confluent.svc.cluster.local:2181
