apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-kafka:6.2.0
    init: confluentinc/confluent-init-container:2.2.0
  dataVolumeCapacity: 5Gi

  listeners:
    external:
      tls:
        enabled: true

  configOverrides:
    server:
      - sasl.enabled.mechanisms=GSSAPI
      - sasl.mechanism.inter.broker.protocol=GSSAPI
      - inter.broker.listener.name=EXTERNAL
      - listener.security.protocol.map=EXTERNAL:SASL_SSL,INTERNAL:PLAINTEXT
      - sasl.kerberos.service.name=kafka

  podTemplate:
    volumes:
      - name: kafka-keytab
        secret:
          secretName: kafka-keytab
    containers:
      - name: kafka
        volumeMounts:
          - name: kafka-keytab
            mountPath: /etc/security/keytabs
            readOnly: true
